/* Türkoğlu: ürün arama ve özel filtreler. */
(function(){
  'use strict';
  async function connectFromSetup(){const u=(document.getElementById('cfgUrl')?.value||'').trim().replace(/\/$/,''),k=(document.getElementById('cfgKey')?.value||'').trim(),m=document.getElementById('authMsg');if(!/^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(u)||!k){if(m)m.textContent='Supabase Proje URL ve Publishable / Anon Key gerekli.';return;}try{localStorage.setItem('turkoglu_sb_cfg',JSON.stringify({u,k}));if(!initClient()||!client)throw Error('Supabase istemcisi oluşturulamadı.');const r=await client.auth.getSession();if(r.error)throw r.error;document.getElementById('setupBox')?.classList.add('hidden');document.getElementById('authBox')?.classList.remove('hidden');if(m)m.textContent='Bağlantı başarılı. Şimdi giriş yapabilirsiniz.';}catch(e){if(m)m.textContent='Bağlantı kurulamadı: '+(e?.message||e);}}
  window.saveConfig=connectFromSetup;
  function loadProfessionalTheme(){if(document.getElementById('turkogluProfessionalTheme'))return;const l=document.createElement('link');l.id='turkogluProfessionalTheme';l.rel='stylesheet';l.href='./theme.css?v=2';document.head.appendChild(l);}
  const brands=['Avenir','Dahua','Hikvision','HiLook','Uniview','Provision-ISR','TVT','TP-Link','Reçber','HES Kablo','Nexans','Mutlusan','Mean Well','Mervesan','Tunçmatik','Seagate','Western Digital','FormRack','NetConnect','Diverse','Standart','Hizmet'];
  const norm=v=>String(v??'').trim().toLocaleLowerCase('tr-TR');
  const unitOf=p=>{const r=norm(p?.unit||p?.birim||'');if(['mt','m','metre'].includes(r))return'mt';if(['adet','ad'].includes(r))return'adet';const t=norm(`${p?.name||''} ${p?.model||''} ${p?.category||''}`),metraj=/kablo|kablo kanal|cat\s*[567]|coax|koaksiyel|elektrik kablosu|data kablosu|enerji kablosu|fiber.*kablo/.test(t),hazir=/hazır|sonlandırılmış|sonlandirilmis|patch cord|patch kablo|hdmi|vga|usb kablo|scart/.test(t);return metraj&&!hazir?'mt':'adet';};
  function css(){if(document.getElementById('tkFilterCss'))return;const s=document.createElement('style');s.id='tkFilterCss';s.textContent='#products .searchbar{display:flex!important;flex-wrap:nowrap!important;align-items:center!important;gap:8px!important;width:100%!important;overflow-x:auto!important}#products .searchbar #productSearch{flex:1 1 auto!important;min-width:240px!important;width:auto!important}#products .searchbar select,#products .searchbar button{flex:0 0 auto!important;width:auto!important;height:40px!important}#products #productBrandFilter{min-width:145px!important}#products #productCategoryFilter{min-width:160px!important}#products #productUnitFilter{min-width:115px!important}#products #stockFilter{min-width:140px!important}';document.head.appendChild(s);}
  function rowProduct(row){const c=row?.cells;if(!c||c.length<4)return null;const n=norm(c[1]?.textContent),m=norm(c[2]?.textContent);try{const a=Array.isArray(window.products)?window.products:[];return a.find(p=>norm(p.name)===n&&(!m||norm(p.model)===m))||a.find(p=>norm(p.name)===n)||null;}catch{return null;}}
  function filter(){const b=norm(document.getElementById('productBrandFilter')?.value||'all'),c=norm(document.getElementById('productCategoryFilter')?.value||'all'),u=norm(document.getElementById('productUnitFilter')?.value||'all'),s=norm(document.getElementById('stockFilter')?.value||'all'),q=norm(document.getElementById('productSearch')?.value||'');document.querySelectorAll('#productRows tr').forEach(r=>{const p=rowProduct(r),cells=r.cells;if(!cells||cells.length<4)return;const okQ=!q||norm(r.textContent).includes(q),okB=b==='all'||norm(p?.brand)===b,okC=c==='all'||norm(cells[3].textContent)===c,okU=u==='all'||unitOf(p||{})===u,st=Number(p?.stock),okS=s==='all'||s==='low'&&st<=5||s==='zero'&&st<=0;r.style.display=okQ&&okB&&okC&&okU&&okS?'':'none';});}
  function options(){const b=document.getElementById('productBrandFilter'),c=document.getElementById('productCategoryFilter');if(!b||!c)return;const ob=b.value,oc=c.value,bs=new Set(brands),cs=new Set();try{(Array.isArray(window.products)?window.products:[]).forEach(p=>{if(p.brand)bs.add(String(p.brand).trim());if(p.category)cs.add(String(p.category).trim());});}catch{}b.innerHTML='<option value="all">Marka: Tümü</option>'+[...bs].sort((x,y)=>x.localeCompare(y,'tr')).map(x=>`<option value="${x.replace(/"/g,'&quot;')}">${x}</option>`).join('');c.innerHTML='<option value="all">Kategori: Tümü</option>'+[...cs].sort((x,y)=>x.localeCompare(y,'tr')).map(x=>`<option value="${x.replace(/"/g,'&quot;')}">${x}</option>`).join('');if([...b.options].some(x=>x.value===ob))b.value=ob;if([...c.options].some(x=>x.value===oc))c.value=oc;filter();}
  function init(){const sec=document.getElementById('products'),bar=sec?.querySelector('.searchbar');if(!bar||document.getElementById('productBrandFilter'))return;css();const mk=(id,text,w)=>{const x=document.createElement('select');x.id=id;x.style.minWidth=w;x.innerHTML=text;x.addEventListener('change',filter);return x;};const b=mk('productBrandFilter','<option value="all">Marka: Tümü</option>','145px'),c=mk('productCategoryFilter','<option value="all">Kategori: Tümü</option>','160px'),u=mk('productUnitFilter','<option value="all">Birim: Tümü</option><option value="adet">Adet</option><option value="mt">mt</option>','115px');const st=document.getElementById('stockFilter');st?.addEventListener('change',filter);const clear=document.createElement('button');clear.className='light';clear.textContent='Temizle';clear.addEventListener('click',()=>{b.value='all';c.value='all';u.value='all';if(st)st.value='all';const q=document.getElementById('productSearch');if(q)q.value='';window.renderProducts?.();setTimeout(filter,30);});bar.append(b,c,u,clear);document.getElementById('productSearch')?.addEventListener('input',()=>setTimeout(filter,0));options();}
  function boot(){loadProfessionalTheme();init();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else setTimeout(boot,0);
})();
