/* Türkoğlu: ürün ve teklif arayüz düzenlemeleri. */
(function(){
'use strict';
const $=id=>document.getElementById(id), norm=v=>String(v??'').trim().toLocaleLowerCase('tr-TR');
function saveConfig(){const u=$('cfgUrl')?.value.trim().replace(/\/$/,''),k=$('cfgKey')?.value.trim(),m=$('authMsg');if(!/^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(u)||!k){if(m)m.textContent='Geçerli Supabase URL ve anahtar gerekli.';return}localStorage.setItem('turkoglu_sb_cfg',JSON.stringify({u,k}));location.reload()}
window.saveConfig=saveConfig;
const productsList=()=>{try{return typeof products!=='undefined'&&Array.isArray(products)?products:[]}catch{return[]}};
const unitOf=p=>{const r=norm(p?.unit||p?.birim||'');if(['mt','m','metre','meter'].includes(r))return'Metre';if(['adet','ad'].includes(r))return'Adet';const t=norm(`${p?.name||p?.product_name||''} ${p?.model||p?.product_model||''} ${p?.category||p?.product_category||''}`),ready=/hazır|hazir|sonlandırılmış|sonlandirilmis|patch cord|patch kablo|hdmi|vga|usb kablo|scart/.test(t);return !ready&&/kablo|cat\s*[567]|koaksiyel|coax|fiber.*kablo|elektrik kablosu|enerji kablosu|kablo kanalı|kablo kanali/.test(t)?'Metre':'Adet'};
function addCss(){if($('tkQuoteCss'))return;const s=document.createElement('style');s.id='tkQuoteCss';s.textContent=`#products .searchbar{display:flex!important;flex-wrap:nowrap!important;align-items:center!important;gap:8px!important;width:100%!important;overflow-x:auto!important}#products .searchbar #productSearch{flex:1 1 auto!important;min-width:240px!important;width:auto!important}#products .searchbar select,#products .searchbar button{flex:0 0 auto!important;width:auto!important;height:40px!important}.quote-filter{width:auto!important;min-width:105px;flex:0 1 125px!important;padding:8px 9px}.quote-filter.search{min-width:185px;flex:1 1 190px!important}.quote-filter-clear{padding:8px 10px!important;white-space:nowrap}.quote-selected-title{font-weight:850;margin:0 0 8px}.quote-actions{justify-content:flex-end!important}.quote-sticky-actions{position:sticky;bottom:0;background:#fff;padding:12px 0 2px;border-top:1px solid #e5e7eb;z-index:8}.product-delete-cell{white-space:nowrap;width:1%}.product-delete-btn{padding:7px 11px!important;background:#b91c1c!important;color:#fff!important;display:inline-block!important;visibility:visible!important;opacity:1!important}.tk-delete-modal{position:fixed;inset:0;background:rgba(15,23,42,.45);display:flex;align-items:center;justify-content:center;z-index:99999;padding:20px}.tk-delete-box{background:#fff;border-radius:14px;max-width:430px;width:100%;padding:22px;box-shadow:0 20px 60px rgba(0,0,0,.25)}.tk-delete-box h3{margin:0 0 8px}.tk-delete-box p{margin:0 0 18px;color:#475569;line-height:1.5}.tk-delete-actions{display:flex;justify-content:flex-end;gap:8px}.tk-delete-actions button{padding:9px 14px;border-radius:8px;border:0;cursor:pointer}.tk-delete-cancel{background:#e5e7eb}.tk-delete-confirm{background:#b91c1c;color:#fff}@media(max-width:760px){.quote-filter{width:100%!important;max-width:none}.quote-filter.search{min-width:100%;flex-basis:100%}.quote-actions{justify-content:flex-end!important}}`;document.head.appendChild(s)}
function rowProduct(row){const list=productsList();if(!list.length)return null;const id=row?.dataset?.productId||row?.getAttribute('data-product-id');if(id){const byId=list.find(p=>String(p.id)===String(id));if(byId)return byId}const text=norm(row?.textContent||'');if(!text)return null;const byExact=list.find(p=>{const n=norm(p.name||p.product_name),m=norm(p.model||p.product_model);return n&&text.includes(n)&&(!m||text.includes(m))});return byExact||list.find(p=>{const n=norm(p.name||p.product_name);return n&&text.includes(n)})||null}
function productClient(){try{const cfg=JSON.parse(localStorage.getItem('turkoglu_sb_cfg')||'null');if(!cfg?.u||!cfg?.k||!window.supabase?.createClient)return null;return window.supabase.createClient(cfg.u,cfg.k)}catch{return null}}
function showDeleteModal(p,onConfirm){const old=$('tkDeleteModal');old?.remove();const m=document.createElement('div');m.id='tkDeleteModal';m.className='tk-delete-modal';m.innerHTML=`<div class="tk-delete-box" role="dialog" aria-modal="true"><h3>Ürünü Sil</h3><p>“${String(p.name||p.product_name||'Bu ürün').replace(/[<>]/g,'')}” ürününü silmek istediğinize emin misiniz?</p><div class="tk-delete-actions"><button type="button" class="tk-delete-cancel">İptal</button><button type="button" class="tk-delete-confirm">Evet, Ürünü Sil</button></div></div>`;document.body.appendChild(m);const close=()=>m.remove();m.querySelector('.tk-delete-cancel').onclick=close;m.querySelector('.tk-delete-confirm').onclick=async()=>{const b=m.querySelector('.tk-delete-confirm');b.disabled=true;b.textContent='Siliniyor...';await onConfirm();if(document.body.contains(m))m.remove()};m.addEventListener('click',e=>{if(e.target===m)close()})}
function productDelete(){const rows=$('productRows');if(!rows)return;const table=rows.closest('table'),head=table?.querySelector('thead tr');if(head&&!head.querySelector('.product-delete-head')){const th=document.createElement('th');th.className='product-delete-head';th.textContent='İşlem';head.appendChild(th)}rows.querySelectorAll('tr').forEach(row=>{if(row.querySelector('.product-delete-cell'))return;const p=rowProduct(row);if(!p?.id)return;const td=document.createElement('td');td.className='product-delete-cell';const btn=document.createElement('button');btn.type='button';btn.className='red product-delete-btn';btn.textContent='Sil';btn.title='Ürünü pasifleştir';btn.onclick=ev=>{ev.preventDefault();ev.stopPropagation();showDeleteModal(p,async()=>{const client=productClient();if(!client){alert('Veritabanı bağlantısı bulunamadı.');return}const {error}=await client.from('products').update({active:false,updated_at:new Date().toISOString()}).eq('id',p.id);if(error){alert('Ürün silinemedi: '+error.message);return}p.active=false;row.remove();optionsProductFilters();applyProductFilters()})};td.appendChild(btn);row.appendChild(td)})}
let productFilterRefs=null;
function optionsProductFilters(){const r=productFilterRefs;if(!r)return;const list=productsList();if(!list.length)return;const bs=[...new Set(list.filter(p=>p.active!==false).map(p=>String(p.brand||'').trim()).filter(Boolean))].sort((a,z)=>a.localeCompare(z,'tr'));const cs=[...new Set(list.filter(p=>p.active!==false).map(p=>String(p.category||'').trim()).filter(Boolean))].sort((a,z)=>a.localeCompare(z,'tr'));const keepB=r.b.value||'all',keepC=r.c.value||'all';r.b.innerHTML='<option value="all">Marka: Tümü</option>'+bs.map(x=>`<option value="${x.replace(/"/g,'&quot;')}">${x}</option>`).join('');r.c.innerHTML='<option value="all">Kategori: Tümü</option>'+cs.map(x=>`<option value="${x.replace(/"/g,'&quot;')}">${x}</option>`).join('');r.b.value=bs.some(x=>norm(x)===norm(keepB))?keepB:'all';r.c.value=cs.some(x=>norm(x)===norm(keepC))?keepC:'all'}
function applyProductFilters(){const r=productFilterRefs;if(!r)return;const bv=norm(r.b.value),cv=norm(r.c.value),uv=norm(r.u.value),sv=r.st?.value||'all',q=norm($('productSearch')?.value);document.querySelectorAll('#productRows tr').forEach(row=>{const p=rowProduct(row);const txt=norm(row.textContent||'');const brand=norm(p?.brand||'');const cat=norm(p?.category||'');const unit=unitOf(p);const stock=Number(p?.stock??0);const active=p?.active!==false;const searchOK=!q||txt.includes(q)||brand.includes(q)||cat.includes(q);const brandOK=bv==='all'||brand===bv;const catOK=cv==='all'||cat===cv;const unitOK=uv==='all'||unit===uv;const stockOK=sv==='all'||(sv==='low'&&stock>0&&stock<=5)||(sv==='zero'&&stock<=0);row.style.display=active&&searchOK&&brandOK&&catOK&&unitOK&&stockOK?'':'none'});productDelete()}
function productPage(){const bar=document.querySelector('#products .searchbar');if(!bar)return;addCss();if(!productFilterRefs){const mk=(id,html,w)=>{const x=document.createElement('select');x.id=id;x.className='quote-filter';x.style.minWidth=w;x.innerHTML=html;return x};const b=mk('productBrandFilter','<option value="all">Marka: Tümü</option>','145px'),c=mk('productCategoryFilter','<option value="all">Kategori: Tümü</option>','160px'),u=mk('productUnitFilter','<option value="all">Birim: Tümü</option><option value="Adet">Adet</option><option value="Metre">Metre</option>','115px'),st=$('stockFilter');const clear=document.createElement('button');clear.type='button';clear.className='light';clear.textContent='Temizle';clear.onclick=()=>{$('productSearch').value='';b.value=c.value=u.value='all';if(st)st.value='all';if(typeof window.renderProducts==='function')window.renderProducts();setTimeout(()=>{optionsProductFilters();applyProductFilters()},80)};bar.append(b,c,u,clear);productFilterRefs={b,c,u,st,clear};[b,c,u].forEach(x=>x.addEventListener('change',applyProductFilters));st?.addEventListener('change',applyProductFilters);$('productSearch')?.addEventListener('input',()=>setTimeout(applyProductFilters,0))}optionsProductFilters();applyProductFilters()}
function quoteFilters(){const root=$('quoteProducts'),head=root?.parentElement?.querySelector('.pagehead');if(!root||!head||head.dataset.qf)return;head.dataset.qf='1';const oldSearch=$('quoteProductSearch'),title=head.querySelector('h3');head.innerHTML='';head.appendChild(title||Object.assign(document.createElement('h3'),{textContent:'Ürün Ekle'}));const vals=field=>[...new Set(productsList().map(p=>String(p?.[field]||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'tr'));const mk=(id,label,arr)=>{const x=document.createElement('select');x.id=id;x.className='quote-filter';x.innerHTML=`<option value="">${label}</option>`+arr.map(v=>`<option value="${v.replace(/"/g,'&quot;')}">${v}</option>`).join('');return x};const b=mk('quoteBrandFilter','Marka',vals('brand')),c=mk('quoteCategoryFilter','Kategori',vals('category')),u=mk('quoteUnitFilter','Birim',['Adet','Metre']),st=mk('quoteStockFilter','Stok',['Stokta var','Stok yok']);const q=oldSearch||document.createElement('input');q.id='quoteProductSearch';q.className='quote-filter search';q.placeholder='Ürün / model ara...';q.oninput=window.filterQuoteProducts;const clear=document.createElement('button');clear.type='button';clear.className='light quote-filter-clear';clear.textContent='Temizle';clear.onclick=()=>{b.value=c.value=u.value=st.value='';q.value='';apply()};[b,c,u,st,q,clear].forEach(x=>head.appendChild(x));[b,c,u,st].forEach(x=>x.addEventListener('change',apply));function apply(){const bv=norm(b.value),cv=norm(c.value),uv=norm(u.value),sv=st.value,qv=norm(q.value);root.querySelectorAll('.p').forEach(card=>{const id=(card.getAttribute('onclick')||'').match(/addQuoteItem\(['\"]([^'\"]+)/)?.[1],p=productsList().find(x=>String(x.id)===String(id)),t=norm(`${p?.name||''} ${p?.brand||''} ${p?.model||''} ${p?.category||''}`);const ok=p?.active!==false&&(!qv||t.includes(qv))&&(!bv||norm(p?.brand)===bv)&&(!cv||norm(p?.category)===cv)&&(!uv||unitOf(p)===uv)&&(!sv||(sv==='Stokta var'?Number(p?.stock)>0:Number(p?.stock)<=0));card.style.display=ok?'':'none'})}window.filterQuoteProducts=apply;apply()}
function moveSelected(){const items=$('qitems'),catalog=$('quoteProducts');if(!items||!catalog)return;const wrap=items.closest('.tablewrap'),catalogWrap=catalog.parentElement;if(!wrap||!catalogWrap||wrap.dataset.moved)return;wrap.dataset.moved='1';if(!wrap.querySelector('.quote-selected-title')){const t=document.createElement('div');t.className='quote-selected-title';t.textContent='Teklife Eklenen Ürünler';wrap.insertBefore(t,wrap.firstChild)}catalogWrap.parentElement.insertBefore(wrap,catalogWrap)}
function alignActions(){const a=[...document.querySelectorAll('#modalBox .actions')].find(x=>[...x.querySelectorAll('button')].some(b=>/Teklifi Kaydet|Kaydet \+ PDF|İptal/.test(b.textContent||'')));if(a)a.classList.add('quote-actions','quote-sticky-actions')}
function quoteUi(){addCss();quoteFilters();moveSelected();alignActions()}
const oe=window.quoteEditor;if(typeof oe==='function'&&!window.__qel){window.__qel=true;window.quoteEditor=function(){const r=oe.apply(this,arguments);setTimeout(quoteUi,20);return r}}
const or=window.renderQuoteDraft;if(typeof or==='function'&&!window.__qrd){window.__qrd=true;window.renderQuoteDraft=function(){const r=or.apply(this,arguments);setTimeout(quoteUi,20);return r}}
function boot(){addCss();productPage();quoteUi()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else setTimeout(boot,0);setInterval(()=>{if($('app')&&!$('app').classList.contains('hidden')){productPage();if($('qitems'))quoteUi()}},500);

/* 5-6: Kontrol paneli doğrulama ve genel UI kalite katmanı. */
function dashboardQuality(){
  const activeProducts=productsList().filter(p=>p?.active!==false);
  const lowStock=activeProducts.filter(p=>Number(p?.stock??0)<=5);
  const openJobs=Array.isArray(window.jobs)?window.jobs.filter(j=>!['Tamamlandı','İptal'].includes(j?.status)):[];
  const doneJobs=Array.isArray(window.jobs)?window.jobs.filter(j=>j?.status==='Tamamlandı'):[];
  const pendingQuotes=Array.isArray(window.quotes)?window.quotes.filter(q=>['Teklif Verildi','Onay Bekliyor'].includes(q?.status)):[];
  const set=(id,value)=>{const el=$(id);if(el)el.textContent=String(value)};
  set('kp',activeProducts.length);
  set('klow',lowStock.length);
  set('kj',openJobs.length);
  set('kd',doneJobs.length);
  set('kqwait',pendingQuotes.length);
  const outstanding=Array.isArray(window.jobs)?window.jobs.reduce((sum,j)=>sum+Math.max(0,Number(j?.remaining_amount)||0),0):0;
  const kr=$('kr');if(kr)kr.textContent=new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(outstanding);
}
const originalDashboard=window.renderDashboard;
if(typeof originalDashboard==='function'&&!window.__dashboardQuality){
  window.__dashboardQuality=true;
  window.renderDashboard=function(){originalDashboard.apply(this,arguments);dashboardQuality()};
}
function addQualityCss(){if($('tkQualityCss'))return;const s=document.createElement('style');s.id='tkQualityCss';s.textContent=`.pagehead{flex-wrap:wrap}.pagehead>.grow{min-width:20px}.actions button,.actions select{max-width:100%}@media(max-width:650px){.pagehead{gap:8px}.pagehead>.grow{display:none}.pagehead>button{width:auto}.card{padding:14px}.kpi{font-size:23px}.tablewrap{max-width:100%;overflow-x:auto;-webkit-overflow-scrolling:touch}.actions{gap:6px}.actions button,.actions select{min-height:40px}.modalbox{max-height:88vh}.searchbar{flex-wrap:wrap}.searchbar>*{min-width:0}}`;document.head.appendChild(s)}
function qualityBoot(){addQualityCss();setTimeout(dashboardQuality,80)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',qualityBoot,{once:true});else qualityBoot();
})();